### PR TITLE
Add support for script flags to filter questions

### PR DESCRIPTION
**Pull request by onlyskin**
Hey!

I had a first go at adding support for testing only certain cases or numbers. I ended up trying out an interface with terminal flags for case and number because it seemed simplest for now rather than making users specify every time by requesting raw input inside the script... what do you think?

I also updated the readme with a few examples of how the flags can be used, and also added another feature idea I had.

I only spent about an hour and half on this so no worries if you have a different idea about a way that would be better, I'm happy to have another go doing it a different way :)

### CODE REVIEW

**Comment by tombusby** [comment]
Thanks a lot for this. I'll take a look over it later. At first glance it looks good though.

**Comment by tombusby** [comment]
I've been having a think about this. I actually intended to implement something like this. My intention is to have multiple modes selected from a menu when you run `polish_case_trainer` rather than invocation flags. That would be a bit more scalable I think.

It's my intention to have multiple modes including verb forms. I'd also like to have the noun/adjective mode and the verb mode further subdivided to a Noun -> Pronouns mode (since they're all totally irregular and just have to be learned) and a mode for verbs that's only the commonly-used/very-irregular basic verbs (to be, to go, etc).

I'm still deciding what to do with the PR. My inclination is to merge this as a temporary solution until I have the time to implement the in-game menu-system.

**Comment by tombusby** [comment]
Ah fuck it, I'll merge it. Just a quick thing though first:

Could you remove that accidentally added space from `README.md` that's on the beginning of the "You'll be presented..." line.

Also, I do actually prefer tabs, but my editor defaulted to spaces when I wrote this, so to keep this consistent could you format `bin/polish_case_trainer` with 4-space indentation.

If you could remove this from the `README.md` "To Do" section that would be good too: (I have something else in mind for that)

"* Add a flag which prints a running score of how many questions were correctly answered every 10 or so questions"

There's also an unhandled error if you supply the CLI flags in an invalid way, e.g.:

* `polish_case_trainer -n p -c` (This produces an IndexError: list index out of range)
* `polish_case_trainer -n -c a` (This just produces an infinite loop that never moves past `(Ctrl+D to exit)`)
* `polish_case_trainer -n u -c z` (Nonsensical values also produce an infinite loop)

If you sort these minor issues and amend the commit I'll be happy to merge :)

**Comment by tombusby** [comment]
I haven't used it myself, but a quick google reveals this module as part of python's standard library:

https://docs.python.org/2/library/argparse.html

That might be worth looking into in terms of parsing the args in a cleaner/easier way.

**Comment by onlyskin** [comment]
Just made the edits you suggested to the README and updated the script to use the argparse standard library - definitely a good call!

**Comment by tombusby** [comment]
One final thing, I promise: could you squash the commits into a single commit. I don't know how familiar you are with this operation, it can be done with `git rebase -i`. If you haven't used it before, I recommend practising on a copy of your branch, since it'll involve using `git push -f` and I'd hate for you to wipe out your commits on origin.

I'd do it myself, but I'm pretty sure I'd end up as the author of the commit, and I'd like to preserve your credit in the contributors tab.

**Comment by onlyskin** [comment]
Done, and thanks :)

**Comment by tombusby** [comment]
Ok, I've just had a look at this, there's a couple of mistakes in `bin/polish_case_trainer`:

```python
    if args.n:
        if not set(args.n).issubset(valid_cases):
            raise ValueError
        numbers = list(args.n)
    if args.c:
        if set(args.c).issubset(valid_cases):
            raise ValueError
        cases = list(args.c)
```
Should be:

```python
    if args.n:
        if not set(args.n).issubset(valid_numbers): # not valid_cases
            raise ValueError
        numbers = list(args.n)
    if args.c:
        if not set(args.c).issubset(valid_cases): # missing not
            raise ValueError
        cases = list(args.c)
```
It's also standard practise to display a "usage" message and then terminate, rather than just throwing a bare, unhandled exception.

[Wikipedia](https://en.wikipedia.org/wiki/Usage_message) has a good overview of their conventions.

Actually, it does look like `argparse` can generate those automatically, and does when you provide a bare option:

```bash
$ polish_case_trainer --n 
usage: polish_case_trainer [-h] [--n N] [--c C]
polish_case_trainer: error: argument --n: expected one argument
```

**Comment by tombusby** [comment]
I've just had a look, you can actually specify the allowed choices using argparse itself. That'll automatically handle invalid args and will print the usage message:

http://stackoverflow.com/questions/15836713/allowing-a-specific-value-for-an-argparse-argument

**Comment by onlyskin** [comment]
I've updated those mistakes - sorry!

I checked out using `argparse` to generate the options, but I don't think it works very well with allowing multiple cases to be specified because it seems that we'd have to provide every combination of cases that a user could specify in the choices list.

We could specify the choices for the numbers flag still though?

**Comment by tombusby** [comment]
Sorry I've taken so long to merge this. Been busy. Just looked over your corrections and things look good.

I'm going to merge, but I've put some thought in to how I want to extend this program so I think I'll be reverting this commit pretty soon though. I'll leave this commit in the history though so you will be included in the contributors.

**Comment by onlyskin** [comment]
Hey no worries, and thanks!

**Pull request merged**
